# Generated by Django 4.2.27 on 2025-12-14 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='outfit_images/%Y/%m/%d/')),
                ('occasion', models.CharField(choices=[('office', 'Office'), ('date', 'Date'), ('college', 'College'), ('casual', 'Casual'), ('formal', 'Formal Event'), ('party', 'Party')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)])),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('suggestions', models.TextField(blank=True)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Outfit Analysis',
                'verbose_name_plural': 'Outfit Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
